package app.ritalog.local;

import android.content.Context;
import android.graphics.Color;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

/** Pixel sprites from assets/www/sprites.js (generated by tools/make_assets.py), shared with the web UI. */
final class Sprites {
    static final class Sprite {
        final int w, h;
        final int[] argb; // row-major, 0 = transparent

        Sprite(int w, int h, int[] argb) {
            this.w = w;
            this.h = h;
            this.argb = argb;
        }
    }

    private static Map<String, Sprite> cache;

    private Sprites() {}

    static synchronized Map<String, Sprite> get(Context c) {
        if (cache != null) return cache;
        Map<String, Sprite> out = new HashMap<>();
        try (InputStream in = c.getAssets().open("www/sprites.js")) {
            ByteArrayOutputStream buf = new ByteArrayOutputStream();
            byte[] chunk = new byte[8192];
            int n;
            while ((n = in.read(chunk)) > 0) buf.write(chunk, 0, n);
            String js = buf.toString(StandardCharsets.UTF_8.name());
            JSONObject all = new JSONObject(js.substring(js.indexOf('{'), js.lastIndexOf('}') + 1));
            for (Iterator<String> it = all.keys(); it.hasNext(); ) {
                String name = it.next();
                JSONObject s = all.getJSONObject(name);
                JSONObject pal = s.getJSONObject("palette");
                Map<Character, Integer> colors = new HashMap<>();
                for (Iterator<String> pk = pal.keys(); pk.hasNext(); ) {
                    String key = pk.next();
                    colors.put(key.charAt(0), Color.parseColor(pal.getString(key)));
                }
                JSONArray rows = s.getJSONArray("rows");
                int h = rows.length(), w = rows.getString(0).length();
                int[] px = new int[w * h];
                for (int y = 0; y < h; y++) {
                    String row = rows.getString(y);
                    for (int x = 0; x < w && x < row.length(); x++) {
                        Integer col = colors.get(row.charAt(x));
                        if (col != null) px[y * w + x] = col;
                    }
                }
                out.put(name, new Sprite(w, h, px));
            }
        } catch (Exception e) {
            // A missing sprite just renders as nothing.
        }
        cache = out;
        return out;
    }
}
